# coding=utf-8
"""Autogenerated (mostly) speed feature tests."""
# https://github.com/pytest-dev/pytest-bdd#test-code-generation-helpers
# https://www.jetbrains.com/help/pycharm/choosing-your-testing-framework.html
# https://www.jetbrains.com/help/pycharm/pytest.html
# https://docs.pytest.org/en/latest/fixture.html#fixture

from pytest_bdd import scenario, given, when, then
import pytest
from car import Car


@pytest.fixture(name='my_car')
def fixture_my_car():
    """Fixture setup."""
    return Car()


@scenario('car.feature', 'Invalid speed')
def test_invalid_speed():
    """Invalid speed."""


@scenario('car.feature', 'Valid speed')
def test_valid_speed():
    """Valid speed."""


@given('Speed is less than 160')
def speed_is_less_than_160(my_car):
    """Speed is less than 160."""
    my_car.speed = 50


@given('Speed is more than 160')
def speed_is_more_than_160(my_car):
    """Speed is more than 160."""
    my_car.speed = 170


@when('Accelerated')
def accelerated(my_car):
    """Accelerated."""
    my_car.accelerate()


@then('Speed is invalid')
def speed_is_invalid(my_car):
    """Speed is invalid."""
    assert not my_car.speed_validate()


@then('Speed is valid')
def speed_is_valid(my_car):
    """Speed is valid."""
    assert my_car.speed_validate()
